Issue #3
veecue/pacman-smartmirror pull request #20
Opened 2019-08-24 20:25 UTC by ventos

2019-08-24 20:32 UTC, rossmeier requested changes

2019-08-24 20:32 UTC, veecue commented on main.go
> +
?

2019-08-24 20:32 UTC, veecue commented on database/repository.go
> +			panic(err)
return wrapped error instead of panicing

2019-08-24 20:32 UTC, veecue commented on database/repository.go
> +			panic("Invalid filename designator: " + str)
ditto

2019-08-24 20:32 UTC, veecue commented on database/repository.go
> +			panic(err)
ditto

2019-08-24 20:32 UTC, veecue commented on database/repository.go
> +			panic(err)
ditto

2019-08-24 20:32 UTC, veecue commented on database/repository.go
> +		readDb = append(readDb, *p)
call a callback here

2019-08-25 11:14 UTC, rossmeier requested changes
Just minor things

2019-08-25 11:14 UTC, veecue commented on main.go
> +
still, wtf?

2019-08-25 11:14 UTC, veecue commented on database/repository.go
> +func ParseDBgunzipped(r io.Reader, cb func(*packet.Packet)) error {
GUnzipped (proper pascal case)

2019-08-25 11:14 UTC, veecue commented on database/repository.go
> +func ParseDBgunzippedSlice(r io.Reader) ([]packet.Packet, error) {
GUnzipped

2019-08-25 11:15 UTC, ventos commented on main.go
> +
still not resolved, ha? :monkey_face:

2019-08-25 11:26 UTC, rossmeier requested changes
LGTM, please rebase on master for merge

2019-08-25 11:52 UTC, rossmeier approved these changes

2019-08-25 11:57 UTC, veecue commented
Got squash-merged on the cli

2019-08-25 11:57 UTC, closed without merging